package com.myspace.sample_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class agents implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.util.List<com.myspace.sample_project.AgentObj> agentObj;

	public agents() {
	}

	public java.util.List<com.myspace.sample_project.AgentObj> getAgentObj() {
		return this.agentObj;
	}

	public void setAgentObj(
			java.util.List<com.myspace.sample_project.AgentObj> agentObj) {
		this.agentObj = agentObj;
	}

	public agents(java.util.List<com.myspace.sample_project.AgentObj> agentObj) {
		this.agentObj = agentObj;
	}

}