package com.myspace.sample_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AgentObj implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("AGENT_POSITION")
	private java.lang.String agentPosition;

	@org.kie.api.definition.type.Label("AGENT_REJOIN")
	private java.lang.Boolean agentRejoin;

	@org.kie.api.definition.type.Label("APPOITMENT_DATE")
	private String appointmentDate;

	@org.kie.api.definition.type.Label("PRODUCTION_AGENT")
	private java.lang.String productionAgent;

	@org.kie.api.definition.type.Label("SERVICING_AGENT")
	private java.lang.String servicingAgent;

	@org.kie.api.definition.type.Label("WORK_MONTH")
	private java.lang.Integer workMonth;

	@org.kie.api.definition.type.Label("COMMISION")
	private Double commision;

	@org.kie.api.definition.type.Label("LICENSE")
	private Boolean license;

	@org.kie.api.definition.type.Label("Error")
	private java.lang.String errorMsg;

	@org.kie.api.definition.type.Label("FYC Total")
	private Double fycTotal;

	@org.kie.api.definition.type.Label("FYC Agent")
	private Double fycAgent;

	@org.kie.api.definition.type.Label("Training")
	private java.lang.Integer training;

	@org.kie.api.definition.type.Label("Join Activities")
	private java.lang.Integer joinActivities;

	@org.kie.api.definition.type.Label("Daily Activities")
	private java.lang.Integer dailyActivities;

	@org.kie.api.definition.type.Label("Policy No")
	private java.lang.String policyNo;

	@org.kie.api.definition.type.Label("Policy Type")
	private java.lang.String policyType;

	@org.kie.api.definition.type.Label("Recal")
	private java.lang.Boolean recal;

	@org.kie.api.definition.type.Label("Recal Amount")
	private java.lang.Integer recalAmount;

	@org.kie.api.definition.type.Label("Monthly Allowance")
	private Double monthlyAllowance;

	@org.kie.api.definition.type.Label("New Amount")
	private Double newAmount;

	@org.kie.api.definition.type.Label("Old Amount")
	private Double oldAmount;

	@org.kie.api.definition.type.Label("Net Amount")
	private Double netAmount;

	public AgentObj() {
	}

	public java.lang.String getAgentPosition() {
		return this.agentPosition;
	}

	public void setAgentPosition(java.lang.String agentPosition) {
		this.agentPosition = agentPosition;
	}

	public java.lang.Boolean getAgentRejoin() {
		return this.agentRejoin;
	}

	public void setAgentRejoin(java.lang.Boolean agentRejoin) {
		this.agentRejoin = agentRejoin;
	}

	public java.lang.String getProductionAgent() {
		return this.productionAgent;
	}

	public void setProductionAgent(java.lang.String productionAgent) {
		this.productionAgent = productionAgent;
	}

	public java.lang.String getServicingAgent() {
		return this.servicingAgent;
	}

	public void setServicingAgent(java.lang.String servicingAgent) {
		this.servicingAgent = servicingAgent;
	}

	public java.lang.Integer getWorkMonth() {
		return this.workMonth;
	}

	public void setWorkMonth(java.lang.Integer workMonth) {
		this.workMonth = workMonth;
	}

	public java.lang.Boolean getLicense() {
		return this.license;
	}

	public void setLicense(java.lang.Boolean license) {
		this.license = license;
	}

	public java.lang.String getAppointmentDate() {
		return this.appointmentDate;
	}

	public void setAppointmentDate(java.lang.String appointmentDate) {
		this.appointmentDate = appointmentDate;
	}

	public java.lang.String getErrorMsg() {
		return this.errorMsg;
	}

	public void setErrorMsg(java.lang.String errorMsg) {
		this.errorMsg = errorMsg;
	}

	public java.lang.Integer getTraining() {
		return this.training;
	}

	public void setTraining(java.lang.Integer training) {
		this.training = training;
	}

	public java.lang.Integer getJoinActivities() {
		return this.joinActivities;
	}

	public void setJoinActivities(java.lang.Integer joinActivities) {
		this.joinActivities = joinActivities;
	}

	public java.lang.Integer getDailyActivities() {
		return this.dailyActivities;
	}

	public void setDailyActivities(java.lang.Integer dailyActivities) {
		this.dailyActivities = dailyActivities;
	}

	public java.lang.String getPolicyNo() {
		return this.policyNo;
	}

	public void setPolicyNo(java.lang.String policyNo) {
		this.policyNo = policyNo;
	}

	public java.lang.String getPolicyType() {
		return this.policyType;
	}

	public void setPolicyType(java.lang.String policyType) {
		this.policyType = policyType;
	}

	public java.lang.Boolean getRecal() {
		return this.recal;
	}

	public void setRecal(java.lang.Boolean recal) {
		this.recal = recal;
	}

	public java.lang.Integer getRecalAmount() {
		return this.recalAmount;
	}

	public void setRecalAmount(java.lang.Integer recalAmount) {
		this.recalAmount = recalAmount;
	}

	public java.lang.Double getCommision() {
		return this.commision;
	}

	public void setCommision(java.lang.Double commision) {
		this.commision = commision;
	}

	public java.lang.Double getFycTotal() {
		return this.fycTotal;
	}

	public void setFycTotal(java.lang.Double fycTotal) {
		this.fycTotal = fycTotal;
	}

	public java.lang.Double getFycAgent() {
		return this.fycAgent;
	}

	public void setFycAgent(java.lang.Double fycAgent) {
		this.fycAgent = fycAgent;
	}

	public java.lang.Double getMonthlyAllowance() {
		return this.monthlyAllowance;
	}

	public void setMonthlyAllowance(java.lang.Double monthlyAllowance) {
		this.monthlyAllowance = monthlyAllowance;
	}

	public java.lang.Double getNewAmount() {
		return this.newAmount;
	}

	public void setNewAmount(java.lang.Double newAmount) {
		this.newAmount = newAmount;
	}

	public java.lang.Double getOldAmount() {
		return this.oldAmount;
	}

	public void setOldAmount(java.lang.Double oldAmount) {
		this.oldAmount = oldAmount;
	}

	public java.lang.Double getNetAmount() {
		return this.netAmount;
	}

	public void setNetAmount(java.lang.Double netAmount) {
		this.netAmount = netAmount;
	}

	public AgentObj(java.lang.String agentPosition,
			java.lang.Boolean agentRejoin, java.lang.String appointmentDate,
			java.lang.String productionAgent, java.lang.String servicingAgent,
			java.lang.Integer workMonth, java.lang.Double commision,
			java.lang.Boolean license, java.lang.String errorMsg,
			java.lang.Double fycTotal, java.lang.Double fycAgent,
			java.lang.Integer training, java.lang.Integer joinActivities,
			java.lang.Integer dailyActivities, java.lang.String policyNo,
			java.lang.String policyType, java.lang.Boolean recal,
			java.lang.Integer recalAmount, java.lang.Double monthlyAllowance,
			java.lang.Double newAmount, java.lang.Double oldAmount,
			java.lang.Double netAmount) {
		this.agentPosition = agentPosition;
		this.agentRejoin = agentRejoin;
		this.appointmentDate = appointmentDate;
		this.productionAgent = productionAgent;
		this.servicingAgent = servicingAgent;
		this.workMonth = workMonth;
		this.commision = commision;
		this.license = license;
		this.errorMsg = errorMsg;
		this.fycTotal = fycTotal;
		this.fycAgent = fycAgent;
		this.training = training;
		this.joinActivities = joinActivities;
		this.dailyActivities = dailyActivities;
		this.policyNo = policyNo;
		this.policyType = policyType;
		this.recal = recal;
		this.recalAmount = recalAmount;
		this.monthlyAllowance = monthlyAllowance;
		this.newAmount = newAmount;
		this.oldAmount = oldAmount;
		this.netAmount = netAmount;
	}

}