package com.myspace.sample_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customers implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Customer Info")
	private java.util.List<com.myspace.sample_project.customerInfo> customerInfo;

	public customers() {
	}

	public java.util.List<com.myspace.sample_project.customerInfo> getCustomerInfo() {
		return this.customerInfo;
	}

	public void setCustomerInfo(
			java.util.List<com.myspace.sample_project.customerInfo> customerInfo) {
		this.customerInfo = customerInfo;
	}

	public customers(
			java.util.List<com.myspace.sample_project.customerInfo> customerInfo) {
		this.customerInfo = customerInfo;
	}

}