package com.myspace.sample_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class customerInfo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "Product")
	private java.lang.String product;

	@org.kie.api.definition.type.Label(value = "Payment Period")
	private java.lang.String paymentPeriod;

	@org.kie.api.definition.type.Label(value = "Comision")
	private java.lang.Integer comision;

	public customerInfo() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.String getPaymentPeriod() {
		return this.paymentPeriod;
	}

	public void setPaymentPeriod(java.lang.String paymentPeriod) {
		this.paymentPeriod = paymentPeriod;
	}

	public java.lang.Integer getComision() {
		return this.comision;
	}

	public void setComision(java.lang.Integer comision) {
		this.comision = comision;
	}

	public customerInfo(java.lang.String name, java.lang.String product,
			java.lang.String paymentPeriod, java.lang.Integer comision) {
		this.name = name;
		this.product = product;
		this.paymentPeriod = paymentPeriod;
		this.comision = comision;
	}

}